export const actions = {
    profile: {
      DATA_FETCHING: "PROFILE_DATA_FETCHING",
      PROFILE_DATA_FETCHED: "PROFILE_DATA_FETCHED",
      PROFILE_DATA_FETCH_ERROR: "PROFILE_DATA_FETCH_ERROR",
      PROFILE_BIO_EDITED: "PROFILE_BIO_EDITED", // Update the action type
      IMAGE_UPDATED: "IMAGE_UPDATED",
      TOGGLE_BLOG_CONTENT_DISPLAY: "TOGGLE_BLOG_CONTENT_DISPLAY",
    },
  };
  