export const actions = {
    profile: {
      DATA_FETCHING: "PROFILE_DATA_FETCHING",
      PROFILE_DATA_FETCHED: "PROFILE_DATA_FETCHED",
      PROFILE_DATA_FETCH_ERROR: "PROFILE_DATA_FETCH_ERROR",
      TOGGLE_BLOG_CONTENT_DISPLAY: "TOGGLE_BLOG_CONTENT_DISPLAY",
    },
  };
  